# Generated by Django 3.2 on 2022-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utr5', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utr5',
            options={'verbose_name_plural': 'UTR5'},
        ),
        migrations.AlterField(
            model_name='utr5',
            name='utr5_seq',
            field=models.TextField(verbose_name='UTR5序列'),
        ),
    ]
