# Generated by Django 3.2 on 2022-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodonCDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, verbose_name='任务编号')),
                ('aa_seq', models.TextField(verbose_name='氨基酸序列')),
                ('dna_seq', models.TextField(verbose_name='DNA序列')),
                ('cai', models.FloatField(verbose_name='CAI值')),
                ('gc', models.FloatField(verbose_name='GC含量')),
                ('energy', models.FloatField(verbose_name='能量值')),
            ],
        ),
        migrations.CreateModel(
            name='GeneAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50, verbose_name='基因ID')),
                ('gene_name', models.CharField(max_length=50, verbose_name='基因名称')),
                ('gene_note', models.TextField(verbose_name='基因备注')),
                ('gene_aa_seq', models.TextField(verbose_name='氨基酸序列')),
                ('gene_default_seq', models.TextField(verbose_name='默认DNA序列')),
                ('gene_optimize_seq', models.TextField(verbose_name='优化DNA序列')),
            ],
        ),
    ]
