# Generated by Django 3.2 on 2022-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneaa',
            name='gene_default_seq',
            field=models.TextField(blank=True, null=True, verbose_name='默认DNA序列'),
        ),
        migrations.AlterField(
            model_name='geneaa',
            name='gene_optimize_seq',
            field=models.TextField(blank=True, null=True, verbose_name='优化DNA序列'),
        ),
    ]
