# Generated by Django 3.2 on 2022-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0002_auto_20220111_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_abbr', models.CharField(max_length=1, verbose_name='氨基酸缩写')),
                ('aa_name', models.CharField(max_length=3, verbose_name='氨基酸简称')),
                ('aa_cn', models.CharField(max_length=20, verbose_name='氨基酸中文')),
                ('aa_attr', models.CharField(max_length=20, verbose_name='氨基酸属性')),
                ('aa_color', models.CharField(max_length=10, verbose_name='颜色表示')),
                ('aa_dna', models.CharField(max_length=100, verbose_name='密码子')),
                ('aa_ratio', models.CharField(max_length=100, verbose_name='密码子比例')),
                ('aa_freq', models.CharField(max_length=100, verbose_name='密码子频率')),
            ],
        ),
    ]
