# Generated by Django 3.2 on 2022-01-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0004_triplet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodonTable',
            new_name='Codon',
        ),
        migrations.RenameModel(
            old_name='GeneAA',
            new_name='Protein',
        ),
        migrations.RenameModel(
            old_name='CodonCDS',
            new_name='Record',
        ),
    ]
