# Generated by Django 3.2 on 2022-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_auto_20220111_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='aa_seq',
            field=models.TextField(blank=True, null=True, verbose_name='氨基酸序列'),
        ),
        migrations.AlterField(
            model_name='record',
            name='cai',
            field=models.FloatField(blank=True, null=True, verbose_name='CAI值'),
        ),
        migrations.AlterField(
            model_name='record',
            name='energy',
            field=models.FloatField(blank=True, null=True, verbose_name='能量值'),
        ),
        migrations.AlterField(
            model_name='record',
            name='gc',
            field=models.FloatField(blank=True, null=True, verbose_name='GC含量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='任务编号'),
        ),
    ]
