# Generated by Django 3.2 on 2022-01-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_rename_datamodel_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
    ]
